services:
  - type: web
    name: backend-ferre
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ferreteria-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
        
    healthCheckPath: /health
    
    # Configuraciones de rendimiento
    disk:
      name: backend-ferre-disk
      mountPath: /opt/render/project/logs
      sizeGB: 1
    
    # Headers y configuraciones de red
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    
    # Variables de entorno adicionales
    envVars:
      - key: PORT
        value: 10000
      - key: RENDER_EXTERNAL_URL
        value: https://backend-ferre.onrender.com

databases:
  - name: ferreteria-db
    plan: free
    databaseName: ferreteria
    user: admin_ferreteria
