services:
  - type: web
    name: backend-ferre
    env: node
    buildCommand: npm install && npm run build && npx prisma migrate deploy && npx prisma generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: ferreteria-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000
    healthCheckPath: /health
